### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#10]
Okay, you are quick.  Thanks for removing autoequip, it causes many problems, with pawns stripping and changing clothing every day. Until the thresholds for changing are increased greatly, I always remove it from any mods I play.

Thanks for adding recycle appeal, but I need to ask why so deep into the research tree? I have it added in at textiles 1, which gives the ability to keep the storage from getting out of hand of all that useless junk the raids bring in, and is better than burning the clothing.

Still working to get github. There are better fitting textures for the endtable.

**Comment by simon-82** [comment]
It is actually added at textiles 1. I have just added the recipe to the tailor's loom which gets unlocked at textiles 1. So crafting 1 then textiles 1 and you have it. Should be early enough before the junk clothing gets out of control. I did it like that because I really want to keep the number of crafting tables down as much as I can. And this one seemed fitting. 
Great idea with the mod btw! Really useful! 

In the ultimate overhaul pack it was handled a bit differently. You could recycle every kind of apparel, no matter if it was made out of stuff or not. But you would always get one kind of ressource - "textile strips". Then you go back to say cloth by combining textile strips with a very small amount of raw cotton. Or hyperweave by combining strips with plasteel bars. 
Still not sure if your solution is better or the idea with the textile strips. 

But you made the endtable mod, right? Loving this little thing! It goes into every bedroom I build. You have an even better texture for it? 

No success getting the github app running?

**Comment by TLHeart** [comment]
Thanks for the clarification on recycle apparel... I was just reading the code. Hopefully Tynan does not change the smelt code, or it will not work... I have tried all the different strip, mend, and don't like them... this one gives back 50% of what the item was made of. Helps keep the clutter down... so long as the item is made from "stuff" it will return usable goods.  

Yes the endtable mod is mine, I just hate the standing lamp...That was my first attempt at making a texture also. Yes there is a much updated texture, nice table with a mini standing lamp covered by a shade. 

Oh the github app is running, just me learning to use it and understand what does what, and making it fit with the way I like to change, update and test.  I am stubborn, and just wanted it to do things my way, but that is not going to happen... no way I can find that it will compare my files to yours. It requires me work within the branch from your master. Oh well, I will get there.

**Comment by simon-82** [comment]
Here is my "workflow" lol. 
- I have my gamefolder somewhere outside the github folder. This is where I do the editing and testing in. The github app is closed all the time btw.
  Most of the time I make edits in various files spread across various folders there. No need to keep track of what has been touched or not. 
- Once I am happy with the changes, I just copy everything (often times the whole Mods and Savedata folder) from my game over to the github folder. As I often also delete stuff, overriding would not get rid of it, so I delete everything first, the copy. Now the beauty of this is, all the previous file information is still there (in the ".git" folder - hidden folder). 
- So this is the time I launch the github app. It will find all the changes and list them. 
  All that is left to do is put in some description on the bottom left and hit the commit button. 
  These changes are now still only local. If I want to go back and add more commits, I go back to step one and add more. 
- Once all is said and done, I press the sync button on the top right. This will upload the commits.

Now you want to do one more step, add a pull request: 
- On the top you should see a timeline. Make sure it's set to your fork first.
- Hit "compare" and select my repository. You should see that your fork is ahead of me now.
- Then you create a pull request (top right) to merge into my repository and bring it up to your point in the timeline. 

Hope that helps :+1:
