### ISSUE TITLE
Strange changes to min and max comfortable temperatures

### ISSUE THREAD

**Issue by ghost** [simon-82/ModVarietyPack#100]
Hi.
I've noticed a strange thing.
After installing some advanced bionic implants minimal comfortable temperature became ~20 degrees centigrade. This results in frostbites and hypothermia in rooms with 21°C.
This is quite frustrating, as they lose consciousness when taking food in the fridge and get frostbites on walks during summer.
Can anything be done?

**Comment by simon-82** [comment]
sounds quite strange indeed. Can you upload a savegame with the error?

I can't really say what's causing that, since bionics don't modify anything related to comf. temps. 
And the log file won't show any errors also, so if I can load your savegame and take a closer look, I might find the cause of that :smile: 

Just the .rws file would be enough. And which version of the modpack you saved it with.
