### ISSUE TITLE
LT no clean please job errors

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#13]
Well, No clean please is throwing errors. 10 jobs in 10 ticks, as the colonist can see the dirt to clean, but it is outside the cleaning zone, but in the home zone...

This is a fresh install to be sure nothing else was causing the problems.

Have used LT no clean please without errors before this. So there is a conflict somewhere.
![screenshot 14](https://cloud.githubusercontent.com/assets/15680072/11018307/054983ea-8581-11e5-8867-a47d2804627c.png)

**Comment by simon-82** [comment]
Yea it looks like he wants to clean that spot, but he can't get there. But he shouldn't clean it because it's out of the cleaning zone. Is he retricted to not be allowed there?

Anyway, I tried to reproduce the error in my game, but I can't. You have a spot in the home, but not in cleaning. I tried that, no errors. Also tried to restrict the cleaner to a zone so he is not allowed. Also works. How did you produce the error? 

Also there are no modifications to any zones in the modpack. You should be able to get the same error in vanilla then.

**Comment by Sephyr** [comment]
Hi there o/

I'm afraid this error might not be excluded to cleaning. I've experienced the same with a downed Ewe that was marked for hunting. Trying to prioritize a pawn leads to it skipping on to the next job or action or when it totally glitches out the pawn will just stand still with the status: Standing (only un-assigning the job through the Work tab gets the pawn unstuck).

The pawns have no area restrictions, i had set up a home zone area just in case of fires and have not touched the cleaning-zone mod or cleaning job priorities at all.
Clean rimworld and modpack 1.12 install.

Here's my output_log (starts at line 240 with a couple of save re-loads to test some stuff)
http://pastebin.com/xiZAAfjp

I've also included my world file and saves prior to the bug and leading up to it with around 7 min intervals.
https://www.dropbox.com/sh/m075cehtdfryoyy/AACWjwMNK9Vyb_flyXXnYL7da?dl=0

I decided to hunt a pack of Ewe's for food since the potatoes werent done yet. Setting my 2 shotgun pawns as nr 1 priority hunters. This however backfired as the pawn Laine got stampeded over when the whole herd turned mad. Leading them back through my chokepoint, they all piled up and got dealt with.

Autosave-4: pre-"Ewe's gone mad" no animals marked, not hunting yet.
Autosave-5: post-"Ewe's gone mad" with the downed animals still marked.
Autosave-1: post-"Ewe's gone mad" - pawns resuming their tasks and start to haul and butcher the dead animals.
Salvation: Discovery of job error and unable to prioritize hunting.

Update: I managed to "fix" it.
Rescueing the Ewe, recruiting the pawn, un-recruit and then prioritize hunting fixed it.
The pawn went on with its regular hunt routine.

**Comment by simon-82** [comment]
I had this hunting error myself and thought I got it fixed. It was actually related to the weapon the guy was using. He would shoot the animal and once it was down he would go close for killing it. The job errors kicked in because the weapon he was using had a minimum range and he couldn't shoot it from that close.
I haven't tried your savegame yet, you were hunting with the shotguns when the error came up, right? 

Btw, you can attach files to your comment here directly.

**Comment by Sephyr** [comment]
Yup shotties,

I tried adding files, but the only ones accepted extensions are image or text-based related.
Paid git feature? 

Funny you mention range, just remembered that the Ewe that is downed on the chunks can't be shot by shotguns or any gun. Something to do with the level they are on when downed in combination of being on chunks (something i often encounter early game due to using chunks as defense measures).
Rescueing the Ewe would solve this as it moves the animal off the chunks.

It's possible that your error is the same as mine, albeit approached from different angles.

**Comment by simon-82** [comment]
Sorry, I was wasn't aware that it could only be images and txt files. 
I can't reproduce the first error related to cleaning yet, so not sure if the two are related. 
I tried your savegames though. 
The only way the downed ewe gets properly hunted is with a weapon that has none of the combat realism features.
Try loading your Savegame-5 and give the hunter an optic rifle or pistol. No errors at all.

**Comment by simon-82** [comment]
There seems to be a bug in CR causing this. Reported this to the mod author. 
I still can't reproduce the LTCleaning error. It always works as expected.
