### ISSUE TITLE
Soil progression

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#52]
Question on the creating soil progression.

Tilled soil, must be place on fertile ground. 
fertilized soil, must be place on tilled soil. needs 3 mulch
water soil, must be place on fertilized soil. needs 1 water
enriched soil, placed on tilled soil. need 6 mulch and 2 water.

logical progression is broken at enhanced soil.
Also makes it very strange to upgrade from watered soil to enriched soil. Cost to upgrade soil one step at a time currently becomes 9 mulch and 3 water to create enriched soil, while if I wait and just create enriched soil from tilled soil, the cost is 6 mulch and 2 water, and less work.

I can see the thought process to be able to jump from tilled to enriched.
But I also see that step by step progression on the soil was started, and makes sense, and as I play and improve the soil then I suddenly need to spend extra resources for no benefit to improve from watered soil to enriched soil.

Actually finally had a colony survive long enough to reach enriched soil.

**Comment by simon-82** [comment]
So my thought process was once you reach enriched soil, you are pretty far in the research tree. 
And if you want to start a new growing zone then, you can straight go to the best one because you have done all the research.
Of course it would be most efficient to wait with upgrading until you have researched all, but it would mean to rush only that research branch. Can be an option if you want to do that. 
Kind of the same is true for power if you think about it.
You can research very far in power and build the more efficient Wind Turbine. It costs only slightly more but is far more efficient. But you would need to only research power branch. But since that is not really good, you build the crappy wind turbine, demolish it and build the better one later.
