### ISSUE TITLE
Unable to install a Stomach

### ISSUE THREAD

**Issue by TinkerObi** [simon-82/ModVarietyPack#66]
After a colonist has lost his stomach, by harvesting or injury, you are unable to install a replacement stomach that's been grown or harvested, (Does not appear on the medical operation list)

Tested on an existing game and a new game. New game cheated research, cheated skills to 20 and removed stomach, option to replace not appearing on list.

**Comment by simon-82** [comment]
I looked at at the unlocks of the stomach recipe.
Recipe was there, but was not unlocked properly. 
Could you check if the same is true for a natural leg? I assume so. 
Thanks for reporting, will fix :+1:

**Comment by OsirisNL** [comment]
Shouldn't there be a races_humanlike.xml in the pack that specifies which recipes there are for humans?

**Comment by simon-82** [comment]
Yep, I have that of course. 
2 things are different though:
- the recipes get unlocked via research. If medicine isn't researched enough, colonists can't install organs. 
- there are other humanlike factions that need the same recipes (Norbals)

**Comment by OsirisNL** [comment]
What I mean is, does InstallNaturalStomach need to be defined in Races_Humanlike.xml? Because in the Core Races_Humanlike.xml only the natural heart, liver, lung and kidney recipes are defined and the pack doesn't come with it's own Races_Humanlike.xml.
Or should the way you made it be enough for it to appear? I'm not that fluent in Rimworld modding yet :)

**Comment by simon-82** [comment]
I am using advanced research from the community core library. In that case the human body basically acts like a workbench, I am assigning a recipe to a thingdef (in this case human or Norbal)

**Comment by simon-82** [comment]
fixed
