### ISSUE TITLE
Need MD2 storage to default to nothing when first built

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#68]
Just a suggestion to prevent problems, the md2 storage default to allow everything at important priority. This can cause save breaking problems. Need to set the initial storage to nothing please.

this is the way mipen handled it.

```
  <defaultStorageSettings>
    <priority>Important</priority>
    <filter>
      <categories>

      </categories>
    </filter>
  </defaultStorageSettings>
</building>
```

Also storing anything that has a quality in MD storage results in weird things happening to the stored items. Items stored become a "copy" of the first item stored. That would explain why the original is limited to manufactured and resources raw.

**Comment by simon-82** [comment]
Thanks, I know. I have it fixed already. Also made a new texture for this thing. Didn't like the old one very much. Tried to make it 1x1 wide, since it only stores on 1 square anyway. Didn't work cause it is the way the dll handles the high stack-count. You will like the new texture though :smile: 

Still not quite finished with what I have planned for the next release. That's why I haven't it uploaded yet...

**Comment by TLHeart** [comment]
That is good. Yea, it needs two cells to work. I still prefer the quantum stock piles. I am still playing 1.21.

**Comment by simon-82** [comment]
fixed
