### ISSUE TITLE
Additional food items in wrong catagories

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#7]
For storage, you have the additional food items spread all over the storage catagories

Sugar and flour are in the manufactured section.
Wheat, oat cocoa, sugarcane.... and more are in raw resources...  please group all the food items under food.

Vegetable garden does a very nice job of grouping the items.

**Comment by simon-82** [comment]
Sugar and flour are manufactured. I think they belong there? 
wheat and the others are raw. They are not food because you can't eat them.
What kind of grouping would you suggest?

**Comment by TLHeart** [comment]
Like I said, all food and food related items need to be grouped in food. Like this;

![screenshot 12](https://cloud.githubusercontent.com/assets/15680072/11005769/0216629c-847d-11e5-9ea4-b1250d6ded4c.png)

If you want to go bug smashing, I can regroup the food items, if I can figure out github

**Comment by simon-82** [comment]
Ah I see. Looks neat and tidy! 
As for github:
Fork the modpack from me in your account. Then you do all the changes you want in your forked version. 
You can download your modified version also and test for errors if you want.
When you are done, you send a pull request to me. So a request to pull all changes of your fork into my version of the modpack. 
It will list all the changes you want to make and we can talk about it again. If we are both fine with the changes I accept the request. Sounds maybe a bit complicated, but it really isn't :+1:

**Comment by TLHeart** [comment]
I really do not get github then.... I do all my modifications on the downloaded mods, on my computer. I can find no way to upload those changes back to my forked copy. Hard to teach an old coder new tricks.

**Comment by simon-82** [comment]
Oh, ok then. 
Sure, I am doing it that way, too. I just thought you wanted to do it in the browser. 
And it would require some more work to set up. So not sure if you wanna do it.

There are actually several ways of doing that. It kinda depends on your operating system though.
Basically you set up a folder where the repository (in this case the modpack) is in, then you use git to sync the changes you make to that folder (your commit) back to the online version on github.

I said there are several ways because you can use a pure command line approach to push commits to your github or you can use a program for that. 
I'm personally just using the official [github app for windows](https://desktop.github.com)
It's easy to set up and does the job. If you have any questions don't hesitate to ask. I'm quite new to github myself but I figured it out pretty fast. 
Looking forward to your first pull request :)
