### ISSUE TITLE
Medical Drink

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#72]
Same problem dismar had with the medical drink, animals will drink it for a meal, until they die. Also trainers will use it to train the animals, and kill them. restriction areas will stop the animal from drinking it on their own, but that does not stop the trainers from using it. 

Reducing the nutrition value to less than 1% fixes the animal problem, but the colonist will still consume it.

Setting the nutrition level to zero, the colonist will not drink it.

**Comment by ghost** [comment]
Animals also consum alcohol- out of bottles. Dogs eat hay. 
Flour and hay should not deteriorate because of not beeing frozen. It does not make any sense. Dry storage is the requirement IRL. Hay should deteriorate over 2 or 2.5 years- IRL the nutrition level drops.
Where is the .xml containing the diet-system? Maybe i can fix at least the problem with the drunken cows.

**Comment by ghost** [comment]
Sorry got sidetracked i would suggest making the medical dring a  useable/ equipment item. because its rarely used/only in specific situations. A doctor can equip it and use it on a sick animal/colonist.

Instead of zoning you can also just forbid the itemstack. When you get a sick person. just send him to eat the medical drink (allow and forbid again). Sadly you can not force animals to do that.

**Comment by simon-82** [comment]
@TLHeart: Setting it to 0 nutrition should work, I guess. If you tell them to drink it, they will drink it, right? The rest of the time, one should forbid the stack. No point in consuming it when they are healthy anyway.  
Making it equippable as weapon is not very feasible I think.

**Comment by TLHeart** [comment]
no with zero nutrition they will not drink it. They just drop it.

**Comment by simon-82** [comment]
Set to 0.5% nutrition now.
Thinking about it, there is 

```
<isPleasureDrug>false</isPleasureDrug>
```

Maybe setting that to true should help some?

**Comment by TLHeart** [comment]
animals will still drink it if their is enough nutrition, regardless of that tag... look at alcohol, animals drink it until they die. 

Now make it a pleasure drug, seems to stop the trainers from using the medical drink to train. 

The problem is with the base game animals eating is no different than the colonists eating.

**Comment by simon-82** [comment]
Ok, so now we have 
- nutrition 0.005
- isPleasureDrug true
- maxNumToIngestAtOnce 1

Not sure if there is more I can do...
