### ISSUE TITLE
Get water from wells uses wood instead of planks

### ISSUE THREAD

**Issue by Ristellise** [simon-82/ModVarietyPack#79]
i am suggesting that there should be a option for wood planks as buckets are usually made from planks but not wood.

**Comment by simon-82** [comment]
I had it that way. Buckets were made from 3 wood planks. I changed it to the cheaper 3 logs / bamboo as suggested by TLHeart for better balancing. 

Consider the amount of water you need for upgrading the soil. It would be too expensive to use the refined ressource (planks) to make all that water you need. To the point where it was debatable to even make upgrading soil worth the cost. 

So, tl:dr, won't change for now because balance. If you have another suggestion for better balance of the buckets, feel free to suggest :smile:
