### ISSUE TITLE
Burger recipes costs out of balance with rest of recipes

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#91]
Burger recipes are just to expensive to make.
Broke the meals down to the harvested ingredients. Work amount is total work involved in producing the needed foods. 1 loaf of bread takes 5 flour, and 300 work, which takes 7.5 grain and 562.5 work. Cheese from milk takes 2.5 milk, and 175 work. 

Fine meals costs 5 meat and 5 veg, total cost 10 food  total work to make 450
      produces 1 meal with 0.9 nutrition, 0.045 joy, +5 mood boost

Simple Burger cost 10 meat, 1 bread(5 flour(7.5 grain)), total cost 17.5 food  and 1462.5 work
      produces 1 burger with 0.85 nutrition, 0.08 joy +5 mood.
      1.75 times the food cost, and triple the work

Cheese Burger cost 10 meat, 1 bread(5flour(7.5 grain)), 1cheese(2.5 milk), total cost 20 food and 1687.5 work. costs even more if soy milk is used.
     Produces 1 cheeseburger with 0.89 nutrition, 0.20 joy, +5 mood. 
    double the food cost, and 4 times the work
     A burgers and the joy tolerance for gluttony becomes a diminishing factor in eating also.

Deluxe Burger costs 10 meat, 1 bread(5flour(7.5)grain)), 1 cheese(2.5) milk, 3 tomatoes, 3 lettuce total 26 food  & 1687.5 work
    Produces 1 deluxe burger, with 1.00 nutrition, 0.30 joy, +10 mood.
    30% joy for gluttony? Fills the joy up so fast they will not choose food for joy. no other joy items are needed in the colony, when 1 meal fills up joy by 30%

Who uses 3 heads of lettuce and 3 tomatoes on one burger?
Why 10 meat per burger? double the meat in a simple and fine meal?

**Comment by simon-82** [comment]
burger 
down to 1 meat / 150 work
up nutrition to 0.95 / joy to 0.09

cheese burger
down to 2 meat / 150 work  / joy to 0.1
up nutrition to 0.98 / mood +10 (so lavish meal boost)

deluxe burger
down to 1 meat / 150 work  / joy to 0.12 / 1 tomato / 1 lettuce
leave nutrition at 1 / mood +10

better that way? 
You did a lot of work to calculate all the values and telling me what is wrong instead of just suggesting better values for the recipes. :stuck_out_tongue:

**Comment by TLHeart** [comment]
Hey, I  had to do the work to be sure that my observations from the game were correct, and so that you could see what I was talking about. As far as the work, I had already done a balance pass over all the meals before, and it was very obvious just how far out your burgers were.

Why would I suggest different recipes, when you rejected most of the previous ones anyway?

As far as balance to the other meals, that is much better.

**Comment by simon-82** [comment]
yea, I know and you did good work with collecting all the values. 
I know you like your cooking and would have believed your judgement here for changed recipes, just so you know.
Oh come on :cry:
You are still salty about your one big pull request that I did (could) not implement? 
I am asking because since that one, you did not want to change anything yourself. Always reporting though, which is also nice of you!

**Comment by simon-82** [comment]
changed recipes as above
