### ISSUE TITLE
Request: additional lighting options

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#94]
Skullwag has updated his path lights so they now work... would love to see them in the pack, along with the wall lights... You already have a ceiling light.

**Comment by simon-82** [comment]
but the path lights can't be colored and I already have lighted walls. And the wall light in the mod you mentioned is just like the porch light I have.
Also, I am currently working on adding new heads with beards. This was not possible until now because hair would dissapear when wearing a hat. These beards stay, even under a helmet :smile: 
![1](https://cloud.githubusercontent.com/assets/14851041/12071835/901e13ee-b0c1-11e5-9b4a-b20e6c25d28d.jpg)

**Comment by TLHeart** [comment]
but path lamps do NOT require a power connection. and they will be able to change color soon.
Variety.... choice, just because you instantly don't see a use you reject it.

The wall light is different from the porch lamp also. but again you reject it, because it is not something you would use...Not everyone wants to use lighted walls, or likes the appearance.

And this is exactly why I no longer do pull request.

And F the beards they are useless.

**Comment by simon-82** [comment]
> Variety.... choice, just because you instantly don't see a use you reject it.

I reject it? I didn't even say I won't include them, lol. I didn't see a use for them, that's all. I don't want to add duplicate items that do the same thing.

> but path lamps do NOT require a power connection. and they will be able to change color soon.

That is nice, I did not know that. Now I see a use for the path lamps. But you haven't answered the question on how the wall lights are different from porch lights. 

> [...]...wants to use lighted walls, likes the appearance. [...] And F the beards they are useless.

You talk about aesthetics on walls and then say adding more appearance options on colonists are useless? Lol. Make up your mind. I could also repeat your argument for you "Variety.... choice, just because you instantly don't see a use you reject it." Right? 

> And this is exactly why I no longer do pull request.

Pull requests are about teamwork. Sometimes I get the impression you are not much of a teamplayer (sorry for that). Ideally, it would work like that: You made a suggestion on adding stuff. We talk about it. We both agree on what do add. You add it and make a pull request.  

You just started coding, adding, changing what you want and throw it at me. No discussion before doing it.
